baseURL = 'https://example.org/'
languageCode = 'fr-FR'
title = 'Cfdt KUHN'
theme = 'hugo-book'
[params]
  # (Optional, default light) Sets color theme: light, dark or auto.
  # Theme 'auto' switches between dark and light modes based on browser/os preferences
  BookTheme = 'light'
  # (Optional, default 'favicon.png') Set the path to a favicon for the site.
  # If the favicon is in /static/custom.svg, then the path would be 'custom.svg'.
  BookFavicon = 'favicon.svg'
  # (Optional, default none) Set the path to a logo for the book. If the logo is
  # /static/logo.png then the path would be 'logo.png'
  BookLogo = 'cfdt-kuhn.svg'
  # (Optional, default docs) Specify section of content to render as menu
  # You can also set value to "*" to render all sections to menu
  BookSection = '*'
